- name: "############### CREATING GRAFANA VOLUMES ###############"
  shell: docker volume create --name grafana_storage | docker volume create --name grafana_data

- name: "############### SETTING UP GRAFANA CONTAINER ###############"
  docker_container:
    name: tick_grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    ports:
    - "3000:3000"
    env:
        GF_INSTALL_PLUGINS=flant-statusmap-panel
    volumes:
    - grafana_storage:/var/lib/grafana
    - grafana_data:/etc/grafana

- name: "############### SETTING UP GRAFANA CONFIGURATION ###############"
  become: yes
  copy:
    src: roles/grafana/files/grafana.ini
    dest: /var/lib/docker/volumes/grafana_data/_data

- name: "############### APPLYING GRAFANA CONFIGURATION ###############"
  shell: docker restart tick_grafana

- name: "############### SETTING UP GRAFANA DASHBOARDS ###############"
  become: yes
  copy:
    src: "{{ item }}"
    dest: /var/lib/docker/volumes/grafana_data/_data/provisioning/dashboards
    owner: root
    mode: 0644
  with_fileglob:
    - roles/grafana/files/GRAFANA_DASHBOARDS/*

- name: "############### APPLYING GRAFANA DASHBOARDS STEP 1 ###############"
  become: yes
  copy:
    src: roles/grafana/files/dashboard.yaml
    dest: /var/lib/docker/volumes/grafana_data/_data/provisioning/dashboards
    owner: root
    mode: 0644

- name: "############### APPLYING GRAFANA DASHBOARDS STEP 2 ###############"
  become: yes
  shell: docker restart tick_grafana