- name: "<.<.<.<.<.<.<.<.<.< INFLUXDB CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_influxdb
    image: influxdb:latest
    state: started
    ports:
    - "8086:8086"
    - "8086:8086/udp"
    env:
        INFLUXDB_DB="db0"
        INFLUXDB_ADMIN_ENABLED="true"
        INFLUXDB_ADMIN_USER="admin"
        INFLUXDB_ADMIN_PASSWORD="it1234"
        INFLUXDB_USER="telegraf"
        INFLUXDB_USER_PASSWORD="telegraf"
    volumes:
    - /influxdb_storage

- name: "<.<.<.<.<.<.<.<.<.< GRAFANA CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_grafana
    image: grafana/grafana:latest
    state: started
    ports:
    - "3000:3000"
    volumes:
    - /grafana_storage

- name: "<.<.<.<.<.<.<.<.<.< KAPACITOR CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_kapacitor
    image: kapacitor:latest
    state: started
    restart_policy: always
    ports:
    - "9092:9092"
    volumes:
    - /kapacitor_storage

- name: "<.<.<.<.<.<.<.<.<.< CHRONOGRAF CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_chronograf
    image: chronograf:latest
    state: started
    restart_policy: always
    ports:
    - "8888:8888"
    volumes:
    - /chronograf_storage
    command: --influxdb-url=http://192.168.85.147:8086

