---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: "INSIRA O ENDEREÇO IP DO HOST DE DESTINO"
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  become: true
  roles:
    - alertas

