---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: "INSERT DESTINATION IP ADDRESS"
    private: no
  - name: target_user
    prompt: "INSERT THE USERNAME"
    private: no
  - name: target_pass
    prompt: "INSERT THE USER'S PASSWORD"
    private: yes
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts
        ansible_user: "{{ target_user }}"
        ansible_ssh_pass: "{{ target_pass }}"

- hosts: dynamically_created_hosts
  become: true
  vars_prompt:
    - name: menu_choice
      prompt: "(ALL THE NECESSARY DEPENDENCIES ARE AUTOMATICALLY INSTALLED)
        \n
        \nPLEASE SELECT ONE OF THE OPTIONS BELOW:
            \n1- INSTALL TICK STACK + GRAFANA
            \n2- INSTALL INFLUXDB + GRAFANA
            \n3- INSTALL INFLUXDB + CHRONOGRAF + KAPACITOR
            \n
            \nINTRODUCE YOUR CHOICE"
      private: no
  roles:
    - dependencies
    - { role: influxdb, when: menu_choice == "1" or menu_choice == "2" or menu_choice == "3" }
    - { role: chronograf, when: menu_choice == "1" or menu_choice == "3" }
    - { role: chronograf_dashboard_deploy, when: menu_choice == "1" or menu_choice == "3"}
    - { role: kapacitor, when: menu_choice == "1" or menu_choice == "3" }
    - { role: alertas, when: menu_choice == "1" or menu_choice == "3"}
    - { role: grafana, when: menu_choice == "1" or menu_choice == "2" }