---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: "INSIRA O ENDEREÇO IP DO HOST DE DESTINO"
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  become: true
  roles:
    - docker

- hosts: dynamically_created_hosts
  become: true
  vars_prompt:
    - name: database
      private: no
      prompt: "INSIRA NOME DA BASE DE DADOS A CRIAR:"
    - name: admin
      private: no
      prompt: "INSIRA USERNAME DE ADMINISTRADOR:"
    - name: admin_password
      private: yes
      prompt: "DEFINA A PASSWORD DE ADMINISTRADOR:"
    - name: user
      private: no
      prompt: "INSIRA O NOME DE UTILIZADOR PARA A BASE DE DADOS:"
    - name: user_password
      private: yes
      prompt: "DEFINA A PASSWORD DO UTILIZADOR:"
  roles:
    - influxdb

- hosts: dynamically_created_hosts
  become: true
  roles:
    - grafana

- hosts: dynamically_created_hosts
  become: true
  roles:
    - kapacitor

- hosts: dynamically_created_hosts
  become: true
  roles:
    - chronograf