---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: "INSIRA O ENDEREÇO IP DO HOST DE DESTINO"
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  become: true
  vars_prompt:
    - name: menu_choice
      prompt: "Para o correto funcionameto e instalação dos diferentes componentes, existe um conjunto de pacotes que devem estar presentes no terminal em cujas diferentes ferramentas serão executadas.
        \n(Todas as dependências são instaladas por omissão quando executado o playbook)
        \n
        \nEscolha uma das seguintes opções(introduza o valor correspondente à opção):
            \n1- Install TICK Stack + Grafana
            \n2- Install Influxdb + Grafana
            \n3- Install Influxdb + Chronograf + Kapacitor
            \n
            \nIntroduza a sua escolha"
      private: no
  roles:
    - dependencies
    - influxdb
    - { role: chronograf, when: menu_choice == "1" or menu_choice == "3" }
    - { role: kapacitor, when: menu_choice == "1" or menu_choice == "3" }
    - { role: grafana, when: menu_choice == "1" or menu_choice == "2" }
