---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: "INSIRA O ENDEREÇO IP DO HOST DE DESTINO"
    private: no
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      with_items: "{{ target_host.split(',') }}"

- hosts: dynamically_created_hosts
  become: true
  vars_prompt:
    - name: influxdb_host
      private: no
      prompt: "INSIRA O ENDEREÇO DO HOST DO INLUXDB (Ex.: 192.168.0.1)"
  roles:
    - telegraf