- name: "################ Copy tickscripts ###################"
  copy:
    src: roles/alertas/tickscripts
    dest: /var/lib/docker/volumes/kapacitor_storage/_data/

- name: "################ Copy tickscripts ###################"
  template:
    src: roles/alertas/template/run_alertas.sh.j2
    dest: /var/lib/docker/volumes/kapacitor_storage/_data/run_alertas.sh

- name: "################ Execute tickscripts ################"
  shell: docker exec tick_kapacitor bash /var/lib/kapacitor/run_alertas.sh

