{
 "title": "DC_SYSTEM_OVERVIEW",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rack",
    "label": "rack",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"rack\""
   },
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\" WHERE rack =~ /^$rack$/"
   },
   {
    "name": "interface",
    "label": "int",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /^$host$/"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /^$host$/"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$host/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "UPTIME $host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "compute1" }
     ]
    }
   ]
  },
  { "title": "CURRENT CPU SELECTED: $cpu", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$host $cpu: USAGE_USER",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(percentile(\"usage_user\", 100), 5s) FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $cpu: USAGE_GUEST",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(percentile(\"usage_guest\", 100), 5s) FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $cpu: USAGE_SYSTEM",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(percentile(\"usage_system\", 100), 5s) FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $cpu: USAGE_IOWAIT",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(percentile(\"usage_iowait\", 100), 5s) FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "CURRENT INTERFACE SELECTED: $interface",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "$host $interface: NET_IN",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s)*8 FROM \"net\" WHERE (\"interface\" =~ /^$interface$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $interface: NET_OUT",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 1s)*8 FROM \"net\" WHERE (\"interface\" =~ /^$interface$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $interface: NET_PACKETS_IN",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE (\"dc\"='datacenter' AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/  AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "$host $interface: NET_PACKETS_OUT",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE (\"dc\"='datacenter' AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/  AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "100" ], "type": "percentile" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  {
   "title": "CURRENT MEMORY USED ON HOST: $host (rack:$rack)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "MEMORY_USAGE",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 38 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") as used FROM \"mem\" WHERE (\"dc\"='datacenter' AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time(1s), *",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=", "value": "datacenter" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "rack", "operator": "=~", "value": "/^$rack$/" }
     ]
    }
   ]
  },
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host:  mem_$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE (\"dc\"='datacenter' AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Use",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_path: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE (\"dc\"='datacenter' AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/  AND \"path\" =~ /^$mountpoint$/) AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DISK I/O REQUEST",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE (\"dc\"='datacenter' AND \"name\" =~/^$disk$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE (\"dc\"='datacenter' AND \"name\" =~/^$disk$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "DISK I/O BYTES",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE (\"dc\"='datacenter' AND \"name\" =~/^$disk$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time($interval), *\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE (\"dc\"='datacenter' AND \"name\" =~/^$disk$/ AND \"host\" =~ /^$host$/ AND \"rack\" =~ /^$rack$/) AND $timeFilter GROUP BY time($interval), *\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DISK I/O TIME",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE (\"dc\" = 'datacenter' AND \"name\" <> sda AND \"host\" <> '_' AND \"rack\" <> '_') AND $timeFilter GROUP BY time($interval), *\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE (\"dc\" = 'datacenter' AND \"name\" <> sda AND \"host\" <> '_' AND \"rack\" <> '_') AND $timeFilter GROUP BY time($interval), *\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SWAP I/O BYTES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dc rack_$tag_rack $tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"in\") as \"in\", mean(\"out\") as \"out\" FROM \"swap\" WHERE (\"dc\" = 'datacenter' AND \"host\" <> '_' AND \"rack\" <> '_' )AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}