- name: <.<.<.<.<.<.<.<.<.< CREATING INFLUXDB VOLUMES >.>.>.>.>.>.>.>.>.>
  shell: docker volume create --name influxdb_storage | docker volume create --name influxdb_data

- name: "<.<.<.<.<.<.<.<.<.< SETTING UP INFLUXDB CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_influxdb
    image: influxdb:latest
    state: started
    ports:
    - "8086:8086"
    - "8086:8086/udp"
    env:
        INFLUXDB_DB="db0"
        INFLUXDB_ADMIN_ENABLED="true"
        INFLUXDB_ADMIN_USER="admin"
        INFLUXDB_ADMIN_PASSWORD="it1234"
        INFLUXDB_USER="telegraf"
        INFLUXDB_USER_PASSWORD="telegraf"
    volumes:
      - influxdb_storage:/var/lib/influxdb
      - influxdb_data:/etc/influxdb

- name: "<.<.<.<.<.<.<.<.<.< SETTNG INFLUXDB CONFIGURATION >.>.>.>.>.>.>.>.>.>"
  copy:
    src: roles/tick/files/influxdb.conf
    dest: /var/lib/docker/volumes/influxdb_data/_data
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: "<.<.<.<.<.<.<.<.<.< APPLYING INFLUXDB CONFIGURATION >.>.>.>.>.>.>.>.>.>"
  shell: docker restart tick_influxdb

- name: <.<.<.<.<.<.<.<.<.< CREATING GRAFANA VOLUMES >.>.>.>.>.>.>.>.>.>
  shell: docker volume create --name grafana_storage | docker volume create --name grafana_data

- name: "<.<.<.<.<.<.<.<.<.< SETTING UP GRAFANA CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_grafana
    image: grafana/grafana:latest
    state: started
    ports:
    - "3000:3000"
    volumes:
    - grafana_storage:/var/lib/grafana
    - grafana_data:/etc/grafana

- name: <.<.<.<.<.<.<.<.<.< CREATING KAPACITOR VOLUMES >.>.>.>.>.>.>.>.>.>
  shell: docker volume create --name kapacitor_data | docker volume create --name kapacitor_storage

- name: "<.<.<.<.<.<.<.<.<.< SETTING UP KAPACITOR CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_kapacitor
    image: kapacitor:latest
    state: started
    ports:
    - "9092:9092"
    volumes:
    - kapacitor_data:/etc/kapacitor
    - kapacitor_storage:/var/lib/kapacitor

- name: "<.<.<.<.<.<.<.<.<.< SETTING KAPACITOR CONFIGURATION >.>.>.>.>.>.>.>.>.>"
  copy:
    src: roles/tick/files/kapacitor.conf
    dest: /var/lib/docker/volumes/kapacitor_data/_data
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: "<.<.<.<.<.<.<.<.<.< APPLYING KAPACITOR CONFIGURATION >.>.>.>.>.>.>.>.>.>"
  shell: docker restart tick_kapacitor

- name: <.<.<.<.<.<.<.<.<.< CREATING CHRONOGRAF VOLUMES >.>.>.>.>.>.>.>.>.>
  shell: docker volume create --name chronograf_storage | docker volume create --name chronograf_data

- name: "<.<.<.<.<.<.<.<.<.< SETTING UP CHRONOGRAF CONTAINER >.>.>.>.>.>.>.>.>.>"
  docker:
    name: tick_chronograf
    image: chronograf:latest
    state: started
    restart_policy: always
    ports:
    - "8888:8888"
    volumes:
    - chronograf_data:/etc/chronograf
    - chronograf_storage:/var/lib/chronograf
    command: --influxdb-url=http://192.168.85.147:8086
