- name: "##############Instalação pacotes essenciais##############"
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python-pip

- pip:
    name:
      - docker 
      - docker-py
    state: forcereinstall

- name: "##############Adicionar chave repositório Docker##############"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
   repo: deb https://download.docker.com/linux/ubuntu bionic stable
   state: present

- name: "##############Atualizar repositórios##############"
  apt:
    update_cache: yes

- name: "##############Instalação Docker##############"
  apt: name={{ item }}
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
